In [1]:
import pandas as pd
import os

In [ ]:
SCRIPT_DIR_PATH = os.getcwd()
PARENT_DIR_PATH = os.path.dirname(SCRIPT_DIR_PATH)
TABLEAU_DATA_DIR_PATH = os.path.join(PARENT_DIR_PATH, "tableau/data")
SSP_RUN_OUTPUT = ""

In [5]:
decomposed_df = pd.read_csv(os.path.join(TABLEAU_DATA_DIR_PATH, "decomposed_emissions_libya_2022_sisepuede_results_sisepuede_run_2025-09-26T10;29;45.200029_WIDE_INPUTS_OUTPUTS.csv"))
decomposed_df.head()

,strategy_id,primary_id,Edgar_Class,CSC.Sector,CSC.Subsector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source,value_original,value_hp
0,0.0,0.0,AG - Crops:CH4,Agriculture,AG - Crops,0.000293,2022,CH4,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.000293,NaN
1,0.0,0.0,AG - Crops:CH4,Agriculture,AG - Crops,0.000284,2023,CH4,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.000284,NaN
2,0.0,0.0,AG - Crops:CH4,Agriculture,AG - Crops,0.000315,2024,CH4,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.000315,NaN
3,0.0,0.0,AG - Crops:CH4,Agriculture,AG - Crops,0.000323,2025,CH4,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.000323,NaN
4,0.0,0.0,AG - Crops:CH4,Agriculture,AG - Crops,0.000332,2026,CH4,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.000332,NaN

In [7]:
decomposed_df["CSC.Subsector"].unique()

array(['AG - Crops', 'AG - Livestock', 'CCSQ', 'EN - Building',
       'EN - Electricity/Heat', 'EN - Fugitive Emissions',
       'EN - Manufacturing/Construction', 'EN - Other',
       'EN - Transportation', 'IN - Industrial Processes',
       'LULUCF - Deforestation', 'LULUCF - Forest Land', 'LULUCF - HWP',
       'LULUCF - Organic Soil', 'LULUCF - Other Land', 'UNACCOUNTED',
       'Waste - Solid Waste', 'Waste - Wastewater Treatment'],
      dtype=object)

In [8]:
ippu_decomposed_df = decomposed_df[decomposed_df["CSC.Subsector"] == "IN - Industrial Processes"]
ippu_decomposed_df.head()

,strategy_id,primary_id,Edgar_Class,CSC.Sector,CSC.Subsector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source,value_original,value_hp
1274,0.0,0.0,IN - Industrial Processes:C2F6,Industrial Processes,IN - Industrial Processes,0.149696,2022,C2F6,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.149696,NaN
1275,0.0,0.0,IN - Industrial Processes:C2F6,Industrial Processes,IN - Industrial Processes,0.145223,2023,C2F6,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.145223,NaN
1276,0.0,0.0,IN - Industrial Processes:C2F6,Industrial Processes,IN - Industrial Processes,0.142560,2024,C2F6,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.142560,NaN
1277,0.0,0.0,IN - Industrial Processes:C2F6,Industrial Processes,IN - Industrial Processes,0.140804,2025,C2F6,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.140804,NaN
1278,0.0,0.0,IN - Industrial Processes:C2F6,Industrial Processes,IN - Industrial Processes,0.140086,2026,C2F6,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.140086,NaN

In [11]:
ippu_filtered_df = ippu_decomposed_df[ippu_decomposed_df["Year"] == 2022]
ippu_filtered_df.head()

,strategy_id,primary_id,Edgar_Class,CSC.Sector,CSC.Subsector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source,value_original,value_hp
1274,0.0,0.0,IN - Industrial Processes:C2F6,Industrial Processes,IN - Industrial Processes,0.149696,2022,C2F6,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.149696,NaN
1323,0.0,0.0,IN - Industrial Processes:C2H3F3,Industrial Processes,IN - Industrial Processes,0.149696,2022,C2H3F3,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.149696,NaN
1372,0.0,0.0,IN - Industrial Processes:C2HF5,Industrial Processes,IN - Industrial Processes,0.149696,2022,C2HF5,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.149696,NaN
1421,0.0,0.0,IN - Industrial Processes:C3F8,Industrial Processes,IN - Industrial Processes,0.149696,2022,C3F8,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.149696,NaN
1470,0.0,0.0,IN - Industrial Processes:C3H2F6,Industrial Processes,IN - Industrial Processes,0.149696,2022,C3H2F6,0.0,0.0,Strategy TX:BASE,LBY,libya,SISEPUEDE,0.149696,NaN

In [12]:
ippu_filtered_df.strategy.unique()

array(['Strategy TX:BASE', 'All Actions', 'Historical'], dtype=object)

In [13]:
ippu_filtered_df.groupby("strategy")["value"].sum()

strategy
All Actions         5.669226
Historical          7.615280
Strategy TX:BASE    5.669226
Name: value, dtype: float64

In [14]:
ippu_filtered_df[ippu_filtered_df["strategy"] == "Historical"]

,strategy_id,primary_id,Edgar_Class,CSC.Sector,CSC.Subsector,value,Year,Gas,design_id,future_id,strategy,Code,Contry,source,value_original,value_hp
7538,NaN,NaN,IN - Industrial Processes:CH4,Industrial Processes,IN - Industrial Processes,0.003465,2022,CH4,NaN,NaN,Historical,LBY,libya,EDGAR,0.003465,NaN
7561,NaN,NaN,IN - Industrial Processes:CO2,Industrial Processes,IN - Industrial Processes,2.499458,2022,CO2,NaN,NaN,Historical,LBY,libya,EDGAR,2.499458,NaN
7584,NaN,NaN,IN - Industrial Processes:HFC,Industrial Processes,IN - Industrial Processes,4.191501,2022,HFC,NaN,NaN,Historical,LBY,libya,EDGAR,4.191501,NaN
7607,NaN,NaN,IN - Industrial Processes:N2O,Industrial Processes,IN - Industrial Processes,0.360349,2022,N2O,NaN,NaN,Historical,LBY,libya,EDGAR,0.360349,NaN
7630,NaN,NaN,IN - Industrial Processes:SF6,Industrial Processes,IN - Industrial Processes,0.560506,2022,SF6,NaN,NaN,Historical,LBY,libya,EDGAR,0.560506,NaN

In [24]:
ippu_filtered_df[(ippu_filtered_df["strategy"] == "Strategy TX:BASE") & (~ippu_filtered_df["Gas"].isin(["CH4", "CO2", "N2O", "SF6"]))]["value"].sum()

np.float64(2.2454469466071436)