In [1]:
import copy
import datetime as dt
from datetime import datetime
import importlib  # needed so that we can reload packages
import logging
import os
import pathlib
import sys
import time
import warnings
from typing import Union, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from utils.logger_utils import setup_clean_logger, mute_external_loggers

# SISEPUEDE imports
from sisepuede.manager.sisepuede_examples import SISEPUEDEExamples
from sisepuede.manager.sisepuede_file_structure import SISEPUEDEFileStructure
import sisepuede.core.support_classes as sc
import sisepuede.transformers as trf
import sisepuede.utilities._plotting as spu
import sisepuede.utilities._toolbox as sf
import sisepuede.core.attribute_table as att
import sisepuede.manager.sisepuede_examples as sxl
import sisepuede.manager.sisepuede_file_structure as sfs
import sisepuede.manager.sisepuede_models as sm
import sisepuede.visualization.plots as svp

# --- Runtime configuration ---
warnings.filterwarnings("ignore")

# Set up a clean logger for your notebook
logger = setup_clean_logger("notebook", logging.INFO)
logger.info("Notebook started successfully.")

# Mute logs from sisepuede to avoid duplication
mute_external_loggers(["sisepuede"])

2026-03-12 17:31:48,082 - INFO - Notebook started successfully.

In [2]:
%load_ext autoreload
%autoreload 2

### Initial Set up

Make sure to edit the config yaml under ssp_modeling/config_files/config.yaml

You can also create a new config yaml

In [3]:
# Set up dir paths

CURR_DIR_PATH = pathlib.Path(os.getcwd())
SSP_MODELING_DIR_PATH = CURR_DIR_PATH.parent
PROJECT_DIR_PATH = SSP_MODELING_DIR_PATH.parent
DATA_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("input_data")
RUN_OUTPUT_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("ssp_run_output")
SCENARIO_MAPPING_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("scenario_mapping")
CONFIG_DIR_PATH = CURR_DIR_PATH.joinpath("config_files")
TRANSFORMATIONS_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("transformations")
MISC_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("misc")
STRATEGIES_DEFINITIONS_FILE_PATH = TRANSFORMATIONS_DIR_PATH.joinpath("strategy_definitions.csv")
STRATEGY_MAPPING_FILE_PATH = MISC_DIR_PATH.joinpath("strategy_mapping.yaml")

In [4]:
from ssp_transformations_handler.GeneralUtils import GeneralUtils
from ssp_transformations_handler.TransformationUtils import TransformationYamlProcessor, StrategyCSVHandler

# Initialize general utilities
g_utils = GeneralUtils()

In [5]:
# Load config file, double check your parameters are correct

YAML_FILE_PATH = os.path.join(CONFIG_DIR_PATH, "config.yaml")
config_params = g_utils.read_yaml(YAML_FILE_PATH)

country_name = config_params['country_name']
ssp_input_file_name = config_params['ssp_input_file_name']
ssp_transformation_cw = config_params['ssp_transformation_cw']
energy_model_flag = config_params['energy_model_flag']
set_lndu_reallocation_factor_to_zero_flag = config_params['set_lndu_reallocation_factor_to_zero']
sim_end_year = config_params.get('sim_end_year', 2050)  # Default to 2050 if not specified

# Print config parameters
logger.info(f"Country name: {country_name}")
logger.info(f"SSP input file name: {ssp_input_file_name}")
logger.info(f"SSP transformation CW: {ssp_transformation_cw}")
logger.info(f"Energy model flag: {energy_model_flag}")
logger.info(f"Set lndu reallocation factor to zero flag: {set_lndu_reallocation_factor_to_zero_flag}")
logger.info(f"Simulation end year: {sim_end_year}")

2026-03-12 17:31:48,184 - INFO - Country name: libya
2026-03-12 17:31:48,184 - INFO - SSP input file name: sisepuede_raw_inputs_latest_LBY_modified_march_2026.csv
2026-03-12 17:31:48,184 - INFO - SSP transformation CW: ssp_libya_transformation_cw_20260310.xlsx
2026-03-12 17:31:48,184 - INFO - Energy model flag: True
2026-03-12 17:31:48,185 - INFO - Set lndu reallocation factor to zero flag: True
2026-03-12 17:31:48,185 - INFO - Simulation end year: 2050

In [6]:
def get_file_structure(
    y0: int = 2015,
    y1: int = sim_end_year,
) -> Tuple[sfs.SISEPUEDEFileStructure, att.AttributeTable]:
    """Get the SISEPUEDE File Structure and update the attribute table
        with new years.
    """
    # setup some SISEPUEDE variables and update time period
    file_struct = sfs.SISEPUEDEFileStructure(
        initialize_directories = False,
    )
 
    # get some keys
    key_time_period = file_struct.model_attributes.dim_time_period
    key_year = file_struct.model_attributes.field_dim_year
 
 
    ##  BUILD THE ATTRIBUTE AND UPDATE
 
    # setup the new attribute table
    years = np.arange(y0, y1 + 1, ).astype(int)
    attribute_time_period = att.AttributeTable(
        pd.DataFrame(
            {
                key_time_period: range(len(years)),
                key_year: years,
            }
        ),
        key_time_period,
    )
 
    # finally, update the ModelAttributes inside the file structure
    (
        file_struct
        .model_attributes
        .update_dimensional_attribute_table(
            attribute_time_period,
        )
    )
 
    # return the tuple
    out = (file_struct, attribute_time_period, )
 
    return out

In [7]:
# Set up SSP objects
INPUT_FILE_PATH = DATA_DIR_PATH.joinpath(ssp_input_file_name)

# model attributes and associated support classes
_EXAMPLES = sxl.SISEPUEDEExamples()
_FILE_STRUCTURE, _ATTRIBUTE_TABLE_TIME_PERIOD = get_file_structure(y1=sim_end_year)
matt = _FILE_STRUCTURE.model_attributes
regions = sc.Regions(matt, )
time_periods = sc.TimePeriods(matt, )

### Making sure our input file has the correct format and correct columns
We use an example df with the complete fields and correct format to make sure our file is in the right shape

In [8]:
##  BUILD BASE INPUTS
df_inputs_raw = pd.read_csv(INPUT_FILE_PATH)

# pull example data to fill in gaps
df_example_input = _EXAMPLES("input_data_frame")

In [9]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw)

Columns in df_example but not in df_input: {'region'}
Columns in df_input but not in df_example: {'iso_alpha_3', 'year'}

In [10]:
all_fields = matt.all_variable_fields_input
df_fiels = df_inputs_raw.columns.tolist()
missing_fields = list(set(all_fields) - set(df_fiels))
print("Missing fields in the input data frame:")
print(missing_fields)

Missing fields in the input data frame:
[]

In [11]:
# Ensure if time_period field exist
if 'time_period' not in df_inputs_raw.columns:
    logger.info("Adding 'time_period' column to df_inputs_raw")
    df_inputs_raw = df_inputs_raw.rename(columns={'period':'time_period'})
else:
    logger.info("'time_period' column already exists in df_inputs_raw")

2026-03-12 17:31:48,892 - INFO - 'time_period' column already exists in df_inputs_raw

In [12]:
# Fixes differences and makes sure that our df is in the correct format.
# Note: Edit this if you need more changes in your df

df_inputs_raw_complete = g_utils.add_missing_cols(df_example_input, df_inputs_raw.copy())
df_inputs_raw_complete.head()

,year,ef_ippu_tonne_nf3_per_tonne_production_chemicals,ef_ippu_tonne_nf3_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_mmm_gdp_other_product_manufacturing,ef_ippu_tonne_sf6_per_tonne_production_chemicals,ef_ippu_tonne_sf6_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_tonne_production_metals,frac_agrc_bevs_and_spices_cl2_dry,frac_agrc_cereals_cl2_dry,frac_agrc_fibers_cl2_dry,...,nemomod_entc_scalar_availability_factor_pp_nuclear,nemomod_entc_scalar_availability_factor_pp_ocean,nemomod_entc_scalar_availability_factor_pp_oil,nemomod_entc_scalar_availability_factor_pp_solar,nemomod_entc_scalar_availability_factor_pp_waste_incineration,nemomod_entc_scalar_availability_factor_pp_wind,iso_alpha_3,population_gnrl_rural,population_gnrl_urban,region
0,2015,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,LBY,795843.0,5735976.0,costa_rica
1,2016,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,LBY,808058.0,5824068.0,costa_rica
2,2017,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,LBY,821006.0,5917764.0,costa_rica
3,2018,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,LBY,834319.0,6014736.0,costa_rica
4,2019,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,LBY,846496.0,6104537.0,costa_rica

In [13]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw_complete)

Columns in df_example but not in df_input: set()
Columns in df_input but not in df_example: {'iso_alpha_3', 'year'}

In [14]:
df_inputs_raw_complete["region"].head()

0    costa_rica
1    costa_rica
2    costa_rica
3    costa_rica
4    costa_rica
Name: region, dtype: object

In [15]:
# Set region to country name
df_inputs_raw_complete['region'] = country_name
df_inputs_raw_complete['region'].head()

0    libya
1    libya
2    libya
3    libya
4    libya
Name: region, dtype: object

In [16]:
# filter to match sim_end_year
print(f"min and max years in raw inputs before filtering: {df_inputs_raw_complete['year'].min()} to {df_inputs_raw_complete['year'].max()}")
df_inputs_raw_complete = df_inputs_raw_complete[df_inputs_raw_complete['year'] <= sim_end_year]
print(f"min and max years in raw inputs after filtering: {df_inputs_raw_complete['year'].min()} to {df_inputs_raw_complete['year'].max()}")

min and max years in raw inputs before filtering: 2015 to 2070
min and max years in raw inputs after filtering: 2015 to 2050

#  Let's try building transformations using this

In [17]:
import sisepuede.transformers as trf
transformers = trf.transformers.Transformers(
    {},
    attr_time_period = _ATTRIBUTE_TABLE_TIME_PERIOD,
    df_input = df_inputs_raw_complete,
)

##  Instantiate some transformations. Make sure to run this cell to create the transformations folder for the first time or if you wish to overwrite

In [18]:
# set an ouput path and instantiate
if not TRANSFORMATIONS_DIR_PATH.exists():
    trf.instantiate_default_strategy_directory(
        transformers,
        TRANSFORMATIONS_DIR_PATH,
    )
else:
    logger.info(f"Directory {TRANSFORMATIONS_DIR_PATH} already exists. Skipping instantiation.")

2026-03-12 17:31:49,374 - INFO - Directory /Users/fabianfuentes/git/ssp_libya/ssp_modeling/transformations already exists. Skipping instantiation.

In [19]:
# Set up the strategy codes you wish to run in ssp
strategies_to_run = [0,6005,6006,6010,6018,6026,6028,6040,6048]
strategies_to_run

[0, 6005, 6006, 6010, 6018, 6026, 6028, 6040, 6048]

### We finished adding new transformation files and strategies so lets load them back

In [20]:
# then, you can load this back in after modifying (play around with it)
transformations = trf.Transformations(
    TRANSFORMATIONS_DIR_PATH,
    transformers = transformers,
)
tab = transformations.attribute_transformation.table

In [21]:
#  build the strategies -- will export to path
t0 = time.time()
strategies = trf.Strategies(
    transformations,
    export_path = "transformations",
    prebuild = True,
)

t_elapse = sf.get_time_elapsed(t0)
print(f"Strategies defined at {strategies.transformations.dir_init} initialized in {t_elapse} seconds")

Strategies defined at /Users/fabianfuentes/git/ssp_libya/ssp_modeling/transformations initialized in 23.08 seconds

In [22]:
strategies.attribute_table

,strategy_id,strategy_code,strategy,description,transformation_specification,baseline_strategy_id
0,0,BASE,Strategy TX:BASE,NaN,TX:BASE,1
1,1000,AGRC:DEC_CH4_RICE,Singleton - Default Value - AGRC: Improve rice...,NaN,TX:AGRC:DEC_CH4_RICE,0
2,1001,AGRC:DEC_EXPORTS,Singleton - Default Value - AGRC: Decrease Exp...,NaN,TX:AGRC:DEC_EXPORTS,0
3,1002,AGRC:DEC_LOSSES_SUPPLY_CHAIN,Singleton - Default Value - AGRC: Reduce suppl...,NaN,TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN,0
4,1003,AGRC:INC_CONSERVATION_AGRICULTURE,Singleton - Default Value - AGRC: Expand conse...,NaN,TX:AGRC:INC_CONSERVATION_AGRICULTURE,0
...,...,...,...,...,...,...
139,6068,WHIRLPOOL:TX:WASO:INC_CAPTURE_BIOGAS,Remove TX:WASO:INC_CAPTURE_BIOGAS from All Act...,NaN,TX:AGRC:DEC_CH4_RICE|TX:AGRC:DEC_EXPORTS|TX:AG...,0
140,6069,WHIRLPOOL:TX:WASO:INC_ENERGY_FROM_BIOGAS,Remove TX:WASO:INC_ENERGY_FROM_BIOGAS from All...,NaN,TX:AGRC:DEC_CH4_RICE|TX:AGRC:DEC_EXPORTS|TX:AG...,0
141,6070,WHIRLPOOL:TX:WASO:INC_ENERGY_FROM_INCINERATION,Remove TX:WASO:INC_ENERGY_FROM_INCINERATION fr...,NaN,TX:AGRC:DEC_CH4_RICE|TX:AGRC:DEC_EXPORTS|TX:AG...,0
142,6071,WHIRLPOOL:TX:WASO:INC_LANDFILLING,Remove TX:WASO:INC_LANDFILLING from All Actions,NaN,TX:AGRC:DEC_CH4_RICE|TX:AGRC:DEC_EXPORTS|TX:AG...,0
143,6072,WHIRLPOOL:TX:WASO:INC_RECYCLING,Remove TX:WASO:INC_RECYCLING from All Actions,NaN,TX:AGRC:DEC_CH4_RICE|TX:AGRC:DEC_EXPORTS|TX:AG...,0

##  Build our templates
- let's use the default variable groupings for LHS

In [23]:
# Building excel templates, make sure to include the strategies ids in the strategies attribute as well as the baseline (0)
df_vargroups = _EXAMPLES("variable_trajectory_group_specification")

strategies.build_strategies_to_templates(
    # df_trajgroup = df_vargroups,
    # include_simplex_group_as_trajgroup = True,
    strategies = strategies_to_run,
)

0

# Finally, load SISEPUEDE and run it

In [24]:
country_name

'libya'

In [25]:
import sisepuede as si
# timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
ssp = si.SISEPUEDE(
    "calibrated",
    db_type = "csv",
    # id_str = f"sisepuede_run_2024-11-04T09:23:26.721580",
    initialize_as_dummy = not(energy_model_flag), # no connection to Julia is initialized if set to True
    regions = [country_name],
    strategies = strategies,
    # try_exogenous_xl_types_in_variable_specification = True,
    attribute_time_period=_ATTRIBUTE_TABLE_TIME_PERIOD
)

2026-03-12 17:32:26,219 - INFO - Successfully initialized SISEPUEDEFileStructure.
2026-03-12 17:32:26,220 - WARNING - Missing key dict_dimensional_keys: key time_series not found. Tables that rely on the time_series will not have index checking.
2026-03-12 17:32:26,220 - INFO - 	Setting export engine to 'csv'.
2026-03-12 17:32:26,221 - WARNING - No index fields defined. Index field values will not be checked when writing to tables.
2026-03-12 17:32:26,221 - INFO - Successfully instantiated table ANALYSIS_METADATA
2026-03-12 17:32:26,221 - WARNING - No index fields found in ATTRIBUTE_DESIGN. Initializing index fields.
2026-03-12 17:32:26,221 - INFO - Successfully instantiated table ATTRIBUTE_DESIGN
2026-03-12 17:32:26,222 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES. Initializing index fields.
2026-03-12 17:32:26,222 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES
2026-03-12 17:32:26,222 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS. Initializing index fields.
2026-03-12 17:32:26,222 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS
2026-03-12 17:32:26,222 - WARNING - No index fields found in ATTRIBUTE_PRIMARY. Initializing index fields.
2026-03-12 17:32:26,222 - INFO - Successfully instantiated table ATTRIBUTE_PRIMARY
2026-03-12 17:32:26,223 - WARNING - No index fields found in ATTRIBUTE_STRATEGY. Initializing index fields.
2026-03-12 17:32:26,223 - INFO - Successfully instantiated table ATTRIBUTE_STRATEGY
2026-03-12 17:32:26,223 - WARNING - No index fields found in ATTRIBUTE_TIME_PERIOD. Initializing index fields.
2026-03-12 17:32:26,223 - INFO - Successfully instantiated table ATTRIBUTE_TIME_PERIOD
2026-03-12 17:32:26,224 - WARNING - No index fields found in MODEL_BASE_INPUT_DATABASE. Initializing index fields.
2026-03-12 17:32:26,224 - INFO - Successfully instantiated table MODEL_BASE_INPUT_DATABASE
2026-03-12 17:32:26,224 - WARNING - No index fields found in MODEL_INPUT. Initializing index fields.
2026-03-12 17:32:26,224 - INFO - Successfully instantiated table MODEL_INPUT
2026-03-12 17:32:26,224 - WARNING - No index fields found in MODEL_OUTPUT. Initializing index fields.
2026-03-12 17:32:26,224 - INFO - Successfully instantiated table MODEL_OUTPUT
2026-03-12 17:32:26,225 - INFO - SISEPUEDEOutputDatabase successfully initialized IterativeDatabase.
2026-03-12 17:32:26,225 - INFO - Successfully initialized database with:
	type:	csv
	analysis id:	sisepuede_run_2026-03-12T17:32:25.916658
	fp_base_output:	/Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-12T17;32;25.916658/sisepuede_run_2026-03-12T17;32;25.916658_output_database
2026-03-12 17:32:26,225 - INFO - Running SISEPUEDE under template data mode 'calibrated'.
2026-03-12 17:32:26,225 - INFO - Initializing BaseInputDatabase
2026-03-12 17:32:27,404 - INFO - Initializing FutureTrajectories
2026-03-12 17:32:30,613 - INFO - Instantiating 1776 sampling units.
2026-03-12 17:32:30,625 - INFO - Iteration 0 complete.
2026-03-12 17:32:34,154 - INFO - Iteration 250 complete.
2026-03-12 17:32:35,937 - INFO - Iteration 500 complete.
2026-03-12 17:32:37,811 - INFO - Iteration 750 complete.
2026-03-12 17:32:39,652 - INFO - Iteration 1000 complete.
2026-03-12 17:32:41,742 - INFO - Iteration 1250 complete.
2026-03-12 17:32:43,790 - INFO - Iteration 1500 complete.
2026-03-12 17:32:45,771 - INFO - Iteration 1750 complete.
2026-03-12 17:32:45,954 - INFO - 	1776 sampling units complete in 15.34 seconds.
2026-03-12 17:32:45,959 - INFO - 	FutureTrajectories for 'libya' complete.
2026-03-12 17:32:45,959 - INFO - Initializing LHSDesign
2026-03-12 17:32:45,960 - INFO - LHSDesign.fields_factors_l reset successful.
2026-03-12 17:32:45,960 - INFO - LHSDesign.fields_factors_x reset successful.
2026-03-12 17:32:45,983 - INFO - 	LHSDesign for region 'libya' complete.
2026-03-12 17:32:45,984 - INFO - Generating primary keys (values of primary_id)...
2026-03-12 17:32:45,984 - INFO - Successfully initialized SISEPUEDEExperimentalManager.
2026-03-12 17:32:45,985 - INFO - Successfully initialized NemoMod temporary database path as /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-03-12 17:32:45,985 - INFO - Set Julia directory for modules and environment to '/Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/julia'.
2026-03-12 17:32:46,037 - INFO - Successfully read NemoMod input table data from /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/ref/nemo_mod/AvailabilityFactor.csv
2026-03-12 17:32:46,038 - INFO - Successfully read NemoMod input table data from /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/ref/nemo_mod/SpecifiedDemandProfile.csv
2026-03-12 17:32:46,091 - INFO - Importing Julia...

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

Precompiling NemoMod...
Info Given NemoMod was explicitly requested, output will be shown live
WARNING: Method definition parse_line(String) in module ConfParser at /Users/fabianfuentes/.julia/packages/ConfParser/b2fge/src/ConfParser.jl:95 overwritten in module NemoMod at /Users/fabianfuentes/.julia/packages/NemoMod/qatsV/src/config_functions.jl:16.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
   1430.7 ms  ? NemoMod
[ Info: Precompiling NemoMod [a3c327a0-d2f0-11e8-37fd-d12fd35c3c72]
WARNING: Method definition parse_line(String) in module ConfParser at /Users/fabianfuentes/.julia/packages/ConfParser/b2fge/src/ConfParser.jl:95 overwritten in module NemoMod at /Users/fabianfuentes/.julia/packages/NemoMod/qatsV/src/config_functions.jl:16.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Info: Skipping precompilation due to precompilable error. Importing NemoMod [a3c327a0-d2f0-11e8-37fd-d12fd35c3c72].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
2026-03-12 17:33:05,985 - INFO - Successfully initialized JuMP optimizer from solver module HiGHS.
2026-03-12 17:33:05,999 - INFO - Successfully initialized SISEPUEDEModels.
2026-03-12 17:33:06,005 - INFO - Table ANALYSIS_METADATA successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-12T17;32;25.916658/sisepuede_run_2026-03-12T17;32;25.916658_output_database/ANALYSIS_METADATA.csv.
2026-03-12 17:33:06,006 - INFO - Table ATTRIBUTE_DESIGN successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-12T17;32;25.916658/sisepuede_run_2026-03-12T17;32;25.916658_output_database/ATTRIBUTE_DESIGN.csv.
2026-03-12 17:33:06,008 - INFO - Table ATTRIBUTE_STRATEGY successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-12T17;32;25.916658/sisepuede_run_2026-03-12T17;32;25.916658_output_database/ATTRIBUTE_STRATEGY.csv.
2026-03-12 17:33:06,009 - INFO - Table ATTRIBUTE_TIME_PERIOD successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-12T17;32;25.916658/sisepuede_run_2026-03-12T17;32;25.916658_output_database/ATTRIBUTE_TIME_PERIOD.csv.
2026-03-12 17:33:06,298 - INFO - Table MODEL_BASE_INPUT_DATABASE successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-12T17;32;25.916658/sisepuede_run_2026-03-12T17;32;25.916658_output_database/MODEL_BASE_INPUT_DATABASE.csv.

In [26]:
not(energy_model_flag)

False

In [ ]:
# This runs the model, make sure you edit key_stretegy with the strategy ids you want to execute include baseline (0)
dict_scens = {
    ssp.key_design: [0],
    ssp.key_future: [0],
    ssp.key_strategy: strategies_to_run,
}

ssp.project_scenarios(
    dict_scens,
    save_inputs = True,
    include_electricity_in_energy = energy_model_flag,
    # dict_optimizer_attributes = {"user_bound_scale": -7, }
)

2026-03-12 17:33:06,353 - INFO -
***	STARTING REGION libya	***

2026-03-12 17:33:07,695 - INFO - Trying run primary_id = 0 in region libya
2026-03-12 17:33:07,695 - INFO - Running AFOLU model
2026-03-12 17:33:07,911 - INFO - AFOLU model run successfully completed
2026-03-12 17:33:07,911 - INFO - Running CircularEconomy model
2026-03-12 17:33:07,934 - INFO - CircularEconomy model run successfully completed
2026-03-12 17:33:07,934 - INFO - Running IPPU model
2026-03-12 17:33:07,971 - INFO - IPPU model run successfully completed
2026-03-12 17:33:07,971 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-12 17:33:07,981 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-12 17:33:08,025 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-12 17:33:08,025 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)
2026-03-12 17:33:08,050 - INFO - 	Path to temporary NemoMod database '/Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite' not found. Creating...

2026-12-Mar 17:33:08.415 Opened SQLite database at /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-12-Mar 17:33:08.432 Added NEMO structure to SQLite database at /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-12-Mar 17:33:23.445 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.

2026-03-12 17:34:14,692 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-03-12 17:34:14,710 - INFO - EnergyProduction model run successfully completed
2026-03-12 17:34:14,711 - INFO - Running Energy (Fugitive Emissions)
2026-03-12 17:34:14,731 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-03-12 17:34:14,731 - INFO - Appending Socioeconomic outputs
2026-03-12 17:34:14,735 - INFO - Socioeconomic outputs successfully appended.
2026-03-12 17:34:14,737 - INFO - Model run for primary_id = 0 successfully completed in 67.04 seconds (n_tries = 1).
2026-03-12 17:34:14,760 - INFO - Trying run primary_id = 76076 in region libya
2026-03-12 17:34:14,761 - INFO - Running AFOLU model

2026-12-Mar 17:33:23.942 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-12-Mar 17:33:41.943 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-12-Mar 17:33:42.020 Started optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-12-Mar 17:34:14.558 Finished optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-03-12 17:34:14,981 - INFO - AFOLU model run successfully completed
2026-03-12 17:34:14,982 - INFO - Running CircularEconomy model
2026-03-12 17:34:15,004 - INFO - CircularEconomy model run successfully completed
2026-03-12 17:34:15,005 - INFO - Running IPPU model
2026-03-12 17:34:15,041 - INFO - IPPU model run successfully completed
2026-03-12 17:34:15,041 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-12 17:34:15,051 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-12 17:34:15,095 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-12 17:34:15,095 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-12-Mar 17:34:15.672 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-12-Mar 17:34:15.718 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].

2026-03-12 17:34:49,673 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-03-12 17:34:49,679 - INFO - EnergyProduction model run successfully completed
2026-03-12 17:34:49,679 - INFO - Running Energy (Fugitive Emissions)
2026-03-12 17:34:49,698 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-03-12 17:34:49,698 - INFO - Appending Socioeconomic outputs
2026-03-12 17:34:49,703 - INFO - Socioeconomic outputs successfully appended.
2026-03-12 17:34:49,705 - INFO - Model run for primary_id = 76076 successfully completed in 34.94 seconds (n_tries = 1).
2026-03-12 17:34:49,707 - INFO - Trying run primary_id = 77077 in region libya
2026-03-12 17:34:49,707 - INFO - Running AFOLU model

2026-12-Mar 17:34:27.351 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-12-Mar 17:34:27.412 Started optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-12-Mar 17:34:49.588 Finished optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-03-12 17:34:49,931 - INFO - AFOLU model run successfully completed
2026-03-12 17:34:49,932 - INFO - Running CircularEconomy model
2026-03-12 17:34:49,955 - INFO - CircularEconomy model run successfully completed
2026-03-12 17:34:49,956 - INFO - Running IPPU model
2026-03-12 17:34:49,993 - INFO - IPPU model run successfully completed
2026-03-12 17:34:49,994 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-12 17:34:50,003 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-12 17:34:50,050 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-12 17:34:50,051 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-12-Mar 17:34:50.994 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-12-Mar 17:34:51.040 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].

2026-03-12 17:35:25,972 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-03-12 17:35:25,988 - INFO - EnergyProduction model run successfully completed
2026-03-12 17:35:25,988 - INFO - Running Energy (Fugitive Emissions)
2026-03-12 17:35:26,011 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-03-12 17:35:26,011 - INFO - Appending Socioeconomic outputs
2026-03-12 17:35:26,016 - INFO - Socioeconomic outputs successfully appended.
2026-03-12 17:35:26,018 - INFO - Model run for primary_id = 77077 successfully completed in 36.31 seconds (n_tries = 1).
2026-03-12 17:35:26,030 - INFO - Trying run primary_id = 81081 in region libya
2026-03-12 17:35:26,030 - INFO - Running AFOLU model

2026-12-Mar 17:35:03.355 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-12-Mar 17:35:03.422 Started optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-12-Mar 17:35:25.867 Finished optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-03-12 17:35:26,253 - INFO - AFOLU model run successfully completed
2026-03-12 17:35:26,254 - INFO - Running CircularEconomy model
2026-03-12 17:35:26,276 - INFO - CircularEconomy model run successfully completed
2026-03-12 17:35:26,277 - INFO - Running IPPU model
2026-03-12 17:35:26,314 - INFO - IPPU model run successfully completed
2026-03-12 17:35:26,314 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-12 17:35:26,324 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-12 17:35:26,369 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-12 17:35:26,369 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-12-Mar 17:35:26.949 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-12-Mar 17:35:27.085 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].

2026-03-12 17:41:58,671 - INFO - NemoMod ran successfully with the following status: OTHER_ERROR
2026-03-12 17:41:58,693 - INFO - EnergyProduction model run successfully completed
2026-03-12 17:41:58,694 - INFO - Running Energy (Fugitive Emissions)

2026-12-Mar 17:35:38.841 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-12-Mar 17:35:38.904 Started optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-12-Mar 17:41:58.479 Finished optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-03-12 17:41:58,717 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-03-12 17:41:58,718 - INFO - Appending Socioeconomic outputs
2026-03-12 17:41:58,723 - INFO - Socioeconomic outputs successfully appended.
2026-03-12 17:41:58,725 - INFO - Model run for primary_id = 81081 successfully completed in 392.7 seconds (n_tries = 1).
2026-03-12 17:41:58,743 - INFO - Trying run primary_id = 89089 in region libya
2026-03-12 17:41:58,744 - INFO - Running AFOLU model
2026-03-12 17:41:58,976 - INFO - AFOLU model run successfully completed
2026-03-12 17:41:58,976 - INFO - Running CircularEconomy model
2026-03-12 17:41:59,005 - INFO - CircularEconomy model run successfully completed
2026-03-12 17:41:59,005 - INFO - Running IPPU model
2026-03-12 17:41:59,047 - INFO - IPPU model run successfully completed
2026-03-12 17:41:59,048 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-12 17:41:59,060 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-12 17:41:59,112 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-12 17:41:59,113 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

2026-12-Mar 17:41:59.717 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.
2026-12-Mar 17:41:59.770 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].

2026-03-12 17:42:35,368 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-03-12 17:42:35,377 - INFO - EnergyProduction model run successfully completed
2026-03-12 17:42:35,378 - INFO - Running Energy (Fugitive Emissions)
2026-03-12 17:42:35,398 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-03-12 17:42:35,399 - INFO - Appending Socioeconomic outputs
2026-03-12 17:42:35,403 - INFO - Socioeconomic outputs successfully appended.
2026-03-12 17:42:35,406 - INFO - Model run for primary_id = 89089 successfully completed in 36.66 seconds (n_tries = 1).
2026-03-12 17:42:35,413 - INFO - Trying run primary_id = 97097 in region libya
2026-03-12 17:42:35,413 - INFO - Running AFOLU model

2026-12-Mar 17:42:12.249 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-12-Mar 17:42:12.320 Started optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-12-Mar 17:42:35.246 Finished optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-03-12 17:42:35,643 - INFO - AFOLU model run successfully completed
2026-03-12 17:42:35,644 - INFO - Running CircularEconomy model
2026-03-12 17:42:35,669 - INFO - CircularEconomy model run successfully completed
2026-03-12 17:42:35,669 - INFO - Running IPPU model
2026-03-12 17:42:35,710 - INFO - IPPU model run successfully completed
2026-03-12 17:42:35,710 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-12 17:42:35,721 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-12 17:42:35,771 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-12 17:42:35,771 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

## Read simulations and check outputs

In [ ]:
# Read input and output files
df_out = ssp.read_output(None)
df_in = ssp.read_input(None)

In [ ]:
def plot_field_stack(
    df,
    fields,
    dict_format,
    time_col="time_period",
    primary_id=0,
    figsize=(18, 8),
    legend_loc='upper right',
    legend_bbox=(1.1, 1),
    ylabel="MT Emissions CO2e",
    xlabel="Time Period",
    title=None,
):
    """
    Plots a stack plot of the selected fields for a given primary_id.

    Args:
        df (pd.DataFrame): DataFrame containing output data.
        fields (list): List of column names to plot.
        dict_format (dict): Formatting dictionary for colors.
        time_col (str): Name of the time column.
        primary_id (int): Value of primary_id to filter.
        figsize (tuple): Figure size.
        legend_loc (str): Legend location.
        legend_bbox (tuple): Legend bbox_to_anchor.
        ylabel (str): Y-axis label.
        xlabel (str): X-axis label.
        title (str): Plot title.
    """
    fig, ax = plt.subplots(figsize=figsize)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if title:
        ax.set_title(title)

    df_plot = df[df[ssp.key_primary].isin([primary_id])]

    fig, ax = spu.plot_stack(
        df_plot,
        fields,
        dict_formatting=dict_format,
        field_x=time_col,
        figtuple=(fig, ax),
    )

    ax.legend(loc=legend_loc, bbox_to_anchor=legend_bbox, title="Fields")
    plt.show()

In [ ]:
# Define the fields to plot and the formatting dictionary
subsector_emission_fields = matt.get_all_subsector_emission_total_fields()

dict_format = dict(
    (k, {"color": v}) for (k, v) in
    matt.get_subsector_color_map().items()
)

In [ ]:
primary_ids_to_plot = df_out[ssp.key_primary].unique()

In [ ]:
# Plot the emissions stack for the primary_id 0 (which is the baseline)
for primary_id in primary_ids_to_plot:

    plot_field_stack(
        df_out,
        subsector_emission_fields,
        dict_format,
        primary_id=primary_id,
        title=f"Emissions Stack Plot for Primary ID {primary_id}"
    )

# Export Wide File

In [ ]:
all_primaries = sorted(list(df_out[ssp.key_primary].unique()))

# build if unable to simply read the data frame
if df_in is None:
    df_in = []
     
    for region in ssp.regions:
        for primary in all_primaries: 
            df_in_filt = ssp.generate_scenario_database_from_primary_key(primary)
            df_in.append(df_in_filt.get(region))
    
    df_in = pd.concat(df_in, axis = 0).reset_index(drop = True)




df_export = pd.merge(
    df_out,
    df_in,
    how = "left",
)



# check output directory 
dir_pkg = os.path.join(
    ssp.file_struct.dir_out, 
    f"sisepuede_summary_results_run_{ssp.id_fs_safe}"
)
os.makedirs(dir_pkg) if not os.path.exists(dir_pkg) else None


for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(dir_pkg, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        print(f"Warning: Table {tab} returned None.")


df_primary = (
    ssp
    .odpt_primary
    .get_indexing_dataframe(
        sorted(list(df_out[ssp.key_primary].unique()))
    )
)
    
df_primary.to_csv(
    os.path.join(dir_pkg, f"ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(dir_pkg, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

In [ ]:
# Getting the directory where the outputs are stored
ssp.file_struct.dir_out

In [ ]:
RUN_ID_OUTPUT_DIR_PATH = os.path.join(
    RUN_OUTPUT_DIR_PATH, 
    f"sisepuede_results_{ssp.id_fs_safe}"
)

os.makedirs(RUN_ID_OUTPUT_DIR_PATH, exist_ok=True)

df_primary.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, "ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        logger.warning(f"Warning: Table {tab} returned None.")

In [ ]:
RUN_ID_OUTPUT_DIR_PATH