In [1]:
import copy
import datetime as dt
from datetime import datetime
import importlib  # needed so that we can reload packages
import logging
import os
import pathlib
import sys
import time
import warnings
from typing import Union, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from utils.logger_utils import setup_clean_logger, mute_external_loggers

# SISEPUEDE imports
from sisepuede.manager.sisepuede_examples import SISEPUEDEExamples
from sisepuede.manager.sisepuede_file_structure import SISEPUEDEFileStructure
import sisepuede.core.support_classes as sc
import sisepuede.transformers as trf
import sisepuede.utilities._plotting as spu
import sisepuede.utilities._toolbox as sf
import sisepuede.core.attribute_table as att
import sisepuede.manager.sisepuede_examples as sxl
import sisepuede.manager.sisepuede_file_structure as sfs
import sisepuede.manager.sisepuede_models as sm
import sisepuede.visualization.plots as svp

# --- Runtime configuration ---
warnings.filterwarnings("ignore")

# Set up a clean logger for your notebook
logger = setup_clean_logger("notebook", logging.INFO)
logger.info("Notebook started successfully.")

# Mute logs from sisepuede to avoid duplication
mute_external_loggers(["sisepuede"])

2026-03-03 12:30:51,975 - INFO - Notebook started successfully.

In [2]:
%load_ext autoreload
%autoreload 2

### Initial Set up

Make sure to edit the config yaml under ssp_modeling/config_files/config.yaml

You can also create a new config yaml

In [3]:
# Set up dir paths

CURR_DIR_PATH = pathlib.Path(os.getcwd())
SSP_MODELING_DIR_PATH = CURR_DIR_PATH.parent
PROJECT_DIR_PATH = SSP_MODELING_DIR_PATH.parent
DATA_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("input_data")
RUN_OUTPUT_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("ssp_run_output")
SCENARIO_MAPPING_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("scenario_mapping")
CONFIG_DIR_PATH = CURR_DIR_PATH.joinpath("config_files")
TRANSFORMATIONS_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("transformations")
MISC_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("misc")
STRATEGIES_DEFINITIONS_FILE_PATH = TRANSFORMATIONS_DIR_PATH.joinpath("strategy_definitions.csv")
STRATEGY_MAPPING_FILE_PATH = MISC_DIR_PATH.joinpath("strategy_mapping.yaml")

In [4]:
from ssp_transformations_handler.GeneralUtils import GeneralUtils
from ssp_transformations_handler.TransformationUtils import TransformationYamlProcessor, StrategyCSVHandler

# Initialize general utilities
g_utils = GeneralUtils()

In [5]:
# Load config file, double check your parameters are correct

YAML_FILE_PATH = os.path.join(CONFIG_DIR_PATH, "config.yaml")
config_params = g_utils.read_yaml(YAML_FILE_PATH)

country_name = config_params['country_name']
ssp_input_file_name = config_params['ssp_input_file_name']
ssp_transformation_cw = config_params['ssp_transformation_cw']
energy_model_flag = config_params['energy_model_flag']
set_lndu_reallocation_factor_to_zero_flag = config_params['set_lndu_reallocation_factor_to_zero']
sim_end_year = config_params.get('sim_end_year', 2050)  # Default to 2050 if not specified

# Print config parameters
logger.info(f"Country name: {country_name}")
logger.info(f"SSP input file name: {ssp_input_file_name}")
logger.info(f"SSP transformation CW: {ssp_transformation_cw}")
logger.info(f"Energy model flag: {energy_model_flag}")
logger.info(f"Set lndu reallocation factor to zero flag: {set_lndu_reallocation_factor_to_zero_flag}")
logger.info(f"Simulation end year: {sim_end_year}")

2026-03-03 12:30:52,072 - INFO - Country name: libya
2026-03-03 12:30:52,072 - INFO - SSP input file name: ssp_libya_inputs_02032026.csv
2026-03-03 12:30:52,072 - INFO - SSP transformation CW: ssp_libya_transformation_cw_20251030.xlsx
2026-03-03 12:30:52,073 - INFO - Energy model flag: True
2026-03-03 12:30:52,073 - INFO - Set lndu reallocation factor to zero flag: True
2026-03-03 12:30:52,073 - INFO - Simulation end year: 2050

In [6]:
def get_file_structure(
    y0: int = 2015,
    y1: int = sim_end_year,
) -> Tuple[sfs.SISEPUEDEFileStructure, att.AttributeTable]:
    """Get the SISEPUEDE File Structure and update the attribute table
        with new years.
    """
    # setup some SISEPUEDE variables and update time period
    file_struct = sfs.SISEPUEDEFileStructure(
        initialize_directories = False,
    )
 
    # get some keys
    key_time_period = file_struct.model_attributes.dim_time_period
    key_year = file_struct.model_attributes.field_dim_year
 
 
    ##  BUILD THE ATTRIBUTE AND UPDATE
 
    # setup the new attribute table
    years = np.arange(y0, y1 + 1, ).astype(int)
    attribute_time_period = att.AttributeTable(
        pd.DataFrame(
            {
                key_time_period: range(len(years)),
                key_year: years,
            }
        ),
        key_time_period,
    )
 
    # finally, update the ModelAttributes inside the file structure
    (
        file_struct
        .model_attributes
        .update_dimensional_attribute_table(
            attribute_time_period,
        )
    )
 
    # return the tuple
    out = (file_struct, attribute_time_period, )
 
    return out

In [7]:
# Set up SSP objects
INPUT_FILE_PATH = DATA_DIR_PATH.joinpath(ssp_input_file_name)

# model attributes and associated support classes
_EXAMPLES = sxl.SISEPUEDEExamples()
_FILE_STRUCTURE, _ATTRIBUTE_TABLE_TIME_PERIOD = get_file_structure(y1=sim_end_year)
matt = _FILE_STRUCTURE.model_attributes
regions = sc.Regions(matt, )
time_periods = sc.TimePeriods(matt, )

### Making sure our input file has the correct format and correct columns
We use an example df with the complete fields and correct format to make sure our file is in the right shape

In [8]:
##  BUILD BASE INPUTS
df_inputs_raw = pd.read_csv(INPUT_FILE_PATH)

# pull example data to fill in gaps
df_example_input = _EXAMPLES("input_data_frame")

In [9]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw)

Columns in df_example but not in df_input: set()
Columns in df_input but not in df_example: {'iso_alpha_3', 'year'}

In [10]:
all_fields = matt.all_variable_fields_input
df_fiels = df_inputs_raw.columns.tolist()
missing_fields = list(set(all_fields) - set(df_fiels))
print("Missing fields in the input data frame:")
print(missing_fields)

Missing fields in the input data frame:
[]

In [11]:
# Ensure if time_period field exist
if 'time_period' not in df_inputs_raw.columns:
    logger.info("Adding 'time_period' column to df_inputs_raw")
    df_inputs_raw = df_inputs_raw.rename(columns={'period':'time_period'})
else:
    logger.info("'time_period' column already exists in df_inputs_raw")

2026-03-03 12:30:52,784 - INFO - 'time_period' column already exists in df_inputs_raw

In [12]:
# Fixes differences and makes sure that our df is in the correct format.
# Note: Edit this if you need more changes in your df

df_inputs_raw_complete = g_utils.add_missing_cols(df_example_input, df_inputs_raw.copy())
df_inputs_raw_complete.head()

No missing columns to add.

,year,ef_ippu_tonne_nf3_per_tonne_production_chemicals,ef_ippu_tonne_nf3_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_mmm_gdp_other_product_manufacturing,ef_ippu_tonne_sf6_per_tonne_production_chemicals,ef_ippu_tonne_sf6_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_tonne_production_metals,frac_agrc_bevs_and_spices_cl2_dry,frac_agrc_cereals_cl2_dry,frac_agrc_fibers_cl2_dry,...,nemomod_entc_scalar_availability_factor_pp_geothermal,nemomod_entc_scalar_availability_factor_pp_hydropower,nemomod_entc_scalar_availability_factor_pp_nuclear,nemomod_entc_scalar_availability_factor_pp_ocean,nemomod_entc_scalar_availability_factor_pp_oil,nemomod_entc_scalar_availability_factor_pp_solar,nemomod_entc_scalar_availability_factor_pp_waste_incineration,nemomod_entc_scalar_availability_factor_pp_wind,iso_alpha_3,region
0,2015,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
1,2016,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
2,2017,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
3,2018,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
4,2019,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya

In [13]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw_complete)

Columns in df_example but not in df_input: set()
Columns in df_input but not in df_example: {'iso_alpha_3', 'year'}

In [14]:
df_inputs_raw_complete["region"].head()

0    libya
1    libya
2    libya
3    libya
4    libya
Name: region, dtype: object

In [15]:
# Set region to country name
df_inputs_raw_complete['region'] = country_name
df_inputs_raw_complete['region'].head()

0    libya
1    libya
2    libya
3    libya
4    libya
Name: region, dtype: object

In [16]:
# filter to match sim_end_year
print(f"min and max years in raw inputs before filtering: {df_inputs_raw_complete['year'].min()} to {df_inputs_raw_complete['year'].max()}")
df_inputs_raw_complete = df_inputs_raw_complete[df_inputs_raw_complete['year'] <= sim_end_year]
print(f"min and max years in raw inputs after filtering: {df_inputs_raw_complete['year'].min()} to {df_inputs_raw_complete['year'].max()}")

min and max years in raw inputs before filtering: 2015 to 2050
min and max years in raw inputs after filtering: 2015 to 2050

#  Let's try building transformations using this

In [17]:
import sisepuede.transformers as trf
transformers = trf.transformers.Transformers(
    {},
    attr_time_period = _ATTRIBUTE_TABLE_TIME_PERIOD,
    df_input = df_inputs_raw_complete,
)

##  Instantiate some transformations. Make sure to run this cell to create the transformations folder for the first time or if you wish to overwrite

In [18]:
# set an ouput path and instantiate
if not TRANSFORMATIONS_DIR_PATH.exists():
    trf.instantiate_default_strategy_directory(
        transformers,
        TRANSFORMATIONS_DIR_PATH,
    )
else:
    logger.info(f"Directory {TRANSFORMATIONS_DIR_PATH} already exists. Skipping instantiation.")

2026-03-03 12:30:53,263 - INFO - Directory /Users/fabianfuentes/git/ssp_libya/ssp_modeling/transformations already exists. Skipping instantiation.

##  --HERE, CUSTOMIZE YOUR TRANSFORMATIONS AND STRATEGIES--

### Customizing transformations and strategies files using TransformationUtils.py classes

In [19]:
# Generate new transformation files based on the excel mapping file. 
# Make sure to have the most updated format for the excel file, check the one used in this notebook for reference.

if ssp_transformation_cw is None:
    logger.warning("ssp_transformation_cw is not defined. Please check your config file.")
else:
    logger.info(f"Using transformation file: {ssp_transformation_cw}")
    cw_file_path = os.path.join(SCENARIO_MAPPING_DIR_PATH, ssp_transformation_cw)
    logger.info(f"Transformation file path: {cw_file_path}")
    excel_yaml_handler = TransformationYamlProcessor(scenario_mapping_excel_path=cw_file_path, yaml_dir_path=TRANSFORMATIONS_DIR_PATH)

2026-03-03 12:30:53,274 - INFO - Using transformation file: ssp_libya_transformation_cw_20251030.xlsx
2026-03-03 12:30:53,275 - INFO - Transformation file path: /Users/fabianfuentes/git/ssp_libya/ssp_modeling/scenario_mapping/ssp_libya_transformation_cw_20251030.xlsx

In [20]:
# This creates transformation yaml files for each strategy in the excel file
if ssp_transformation_cw is not None:
    logger.info("Processing YAML files...")
    excel_yaml_handler.process_yaml_files()
else:
    logger.warning("ssp_transformation_cw is not defined. Please check your config file.")

2026-03-03 12:30:53,362 - INFO - Processing YAML files...

==================================================
[transformation_entc_target_renewable_elec.yaml | TX:ENTC:TARGET_RENEWABLE_ELEC] 95% of electricity is generated by renewables in 2050 (ENTC) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_entc_target_renewable_elec.yaml | TX:ENTC:TARGET_RENEWABLE_ELEC] 95% of electricity is generated by renewables in 2050 (ENTC) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_fgtv_dec_leaks.yaml | TX:FGTV:DEC_LEAKS] Minimize leaks (FGTV) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_fgtv_dec_leaks.yaml | TX:FGTV:DEC_LEAKS] Minimize leaks (FGTV) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_fgtv_inc_flare.yaml | TX:FGTV:INC_FLARE] Maximize flaring (FGTV) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_fgtv_inc_flare.yaml | TX:FGTV:INC_FLARE] Maximize flaring (FGTV) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_ippu_dec_clinker.yaml | TX:IPPU:DEC_CLINKER] Reduce cement clinker (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.8
==================================================
==================================================
[transformation_ippu_dec_demand.yaml | TX:IPPU:DEC_DEMAND] Demand management (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.7
==================================================
==================================================
[transformation_ippu_dec_hfcs.yaml | TX:IPPU:DEC_HFCS] Reduce use of HFCs (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 2.0
==================================================
==================================================
[transformation_ippu_dec_n2o.yaml | TX:IPPU:DEC_N2O] Reduce Nitrous Oxide emissions (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 2.0
==================================================
==================================================
[transformation_ippu_dec_other_fcs.yaml | TX:IPPU:DEC_OTHER_FCS] Reduce other fluorinated compounds (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 2.0
==================================================
==================================================
[transformation_ippu_dec_pfcs.yaml | TX:IPPU:DEC_PFCS] Reduce use of PFCs (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 2.0
==================================================
==================================================
[transformation_lsmm_inc_capture_biogas.yaml | TX:LSMM:INC_CAPTURE_BIOGAS] Increase biogas capture at anaerobic decomposition facilities (LSMM) | Start: 12
Strategy: strategy_NDC, Scalar value: 1.0
==================================================
==================================================
[transformation_lsmm_inc_capture_biogas.yaml | TX:LSMM:INC_CAPTURE_BIOGAS] Increase biogas capture at anaerobic decomposition facilities (LSMM) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_lsmm_inc_management_cattle_pigs.yaml | TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS] Improve manure management for cattle and pigs (LSMM) | Start: 12
Strategy: strategy_NDC, Scalar value: 1.0
YAML file transformation_lsmm_inc_management_cattle_pigs.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_lsmm_inc_management_cattle_pigs.yaml | TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS] Improve manure management for cattle and pigs (LSMM) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_lsmm_inc_management_cattle_pigs.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_lsmm_inc_management_other.yaml | TX:LSMM:INC_MANAGEMENT_OTHER] Improve manure management for other animals (LSMM) | Start: 12
Strategy: strategy_NDC, Scalar value: 1.0
YAML file transformation_lsmm_inc_management_other.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_lsmm_inc_management_other.yaml | TX:LSMM:INC_MANAGEMENT_OTHER] Improve manure management for other animals (LSMM) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_lsmm_inc_management_other.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_lsmm_inc_management_poultry.yaml | TX:LSMM:INC_MANAGEMENT_POULTRY] Improve manure management for poultry (LSMM) | Start: 12
Strategy: strategy_NDC, Scalar value: 1.0
YAML file transformation_lsmm_inc_management_poultry.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_lsmm_inc_management_poultry.yaml | TX:LSMM:INC_MANAGEMENT_POULTRY] Improve manure management for poultry (LSMM) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_lsmm_inc_management_poultry.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_lvst_dec_enteric_fermentation.yaml | TX:LVST:DEC_ENTERIC_FERMENTATION] Reduce enteric fermentation (LVST) | Start: 12
Strategy: strategy_NDC, Scalar value: 1.0
YAML file transformation_lvst_dec_enteric_fermentation.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_lvst_dec_enteric_fermentation.yaml | TX:LVST:DEC_ENTERIC_FERMENTATION] Reduce enteric fermentation (LVST) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_lvst_dec_enteric_fermentation.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_lvst_dec_exports.yaml | TX:LVST:DEC_EXPORTS] Decrease exports (LVST) | Start: 12
Strategy: strategy_NDC, Scalar value: 1.0
==================================================
==================================================
[transformation_lvst_dec_exports.yaml | TX:LVST:DEC_EXPORTS] Decrease exports (LVST) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.5
==================================================
==================================================
[transformation_lvst_inc_productivity.yaml | TX:LVST:INC_PRODUCTIVITY] Increase livestock productivity (LVST) | Start: 12
Strategy: strategy_NDC, Scalar value: 1.0
==================================================
==================================================
[transformation_lvst_inc_productivity.yaml | TX:LVST:INC_PRODUCTIVITY] Increase livestock productivity (LVST) | Start: 12
Strategy: strategy_LEP, Scalar value: 2.0
==================================================
==================================================
[transformation_pflo_inc_healthier_diets.yaml | TX:PFLO:INC_HEALTHIER_DIETS] Change diets (PFLO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.5
YAML file transformation_pflo_inc_healthier_diets.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_pflo_inc_ind_ccs.yaml | TX:PFLO:INC_IND_CCS] Industrial carbon capture and sequestration (PFLO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.5
YAML file transformation_pflo_inc_ind_ccs.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_scoe_dec_demand_heat.yaml | TX:SCOE:DEC_DEMAND_HEAT] Reduce end-use demand for heat energy by improving building shell (SCOE) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_scoe_dec_demand_heat.yaml | TX:SCOE:DEC_DEMAND_HEAT] Reduce end-use demand for heat energy by improving building shell (SCOE) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_scoe_shift_fuel_heat.yaml | TX:SCOE:SHIFT_FUEL_HEAT] Switch to electricity for heat using heat pumps, electric stoves, etc. (SCOE) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_scoe_shift_fuel_heat.yaml | TX:SCOE:SHIFT_FUEL_HEAT] Switch to electricity for heat using heat pumps, electric stoves, etc. (SCOE) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_trde_dec_demand.yaml | TX:TRDE:DEC_DEMAND] Reduce demand for transport (TRDE) | Start: 12
Strategy: strategy_LEP, Scalar value: 3.0
==================================================
==================================================
[transformation_trns_inc_occupancy_light_duty.yaml | TX:TRNS:INC_OCCUPANCY_LIGHT_DUTY] Increase occupancy for private vehicles (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 3.0
==================================================
==================================================
[transformation_trns_shift_fuel_light_duty.yaml | TX:TRNS:SHIFT_FUEL_LIGHT_DUTY] Electrify light duty road transport (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_trns_shift_fuel_light_duty.yaml | TX:TRNS:SHIFT_FUEL_LIGHT_DUTY] Electrify light duty road transport (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_trns_shift_fuel_maritime.yaml | TX:TRNS:SHIFT_FUEL_MARITIME] Fuel switch maritime (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_trns_shift_fuel_maritime.yaml | TX:TRNS:SHIFT_FUEL_MARITIME] Fuel switch maritime (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_trns_shift_fuel_medium_duty.yaml | TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY] Fuel switch medium duty road transport (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_trns_shift_fuel_medium_duty.yaml | TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY] Fuel switch medium duty road transport (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_trns_shift_fuel_rail.yaml | TX:TRNS:SHIFT_FUEL_RAIL] Electrify rail (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.5
==================================================
==================================================
[transformation_trns_shift_fuel_rail.yaml | TX:TRNS:SHIFT_FUEL_RAIL] Electrify rail (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_trns_shift_mode_freight.yaml | TX:TRNS:SHIFT_MODE_FREIGHT] Mode shift freight (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 2.0
==================================================
==================================================
[transformation_trns_shift_mode_passenger.yaml | TX:TRNS:SHIFT_MODE_PASSENGER] Mode shift passenger vehicles to others (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 2.0
==================================================
==================================================
[transformation_trns_shift_mode_regional.yaml | TX:TRNS:SHIFT_MODE_REGIONAL] Mode shift regional passenger travel (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_trns_shift_mode_regional.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_trww_inc_capture_biogas.yaml | TX:TRWW:INC_CAPTURE_BIOGAS] Increase biogas capture (TRWW) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_trww_inc_compliance_septic.yaml | TX:TRWW:INC_COMPLIANCE_SEPTIC] Increase septic compliance (TRWW) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_wali_inc_treatment_industrial.yaml | TX:WALI:INC_TREATMENT_INDUSTRIAL] Improved industrial wastewater treatment (WALI) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_wali_inc_treatment_industrial.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_wali_inc_treatment_rural.yaml | TX:WALI:INC_TREATMENT_RURAL] Improved rural wastewater treatment (WALI) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_wali_inc_treatment_rural.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_wali_inc_treatment_urban.yaml | TX:WALI:INC_TREATMENT_URBAN] Improved urban wastewater treatment (WALI) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
YAML file transformation_wali_inc_treatment_urban.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_waso_dec_consumer_food_waste.yaml | TX:WASO:DEC_CONSUMER_FOOD_WASTE] Consumer food waste reduction (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_waso_inc_capture_biogas.yaml | TX:WASO:INC_CAPTURE_BIOGAS] Increase biogas capture (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_waso_inc_energy_from_biogas.yaml | TX:WASO:INC_ENERGY_FROM_BIOGAS] Biogas for energy production (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_waso_inc_energy_from_incineration.yaml | TX:WASO:INC_ENERGY_FROM_INCINERATION] Incineration for energy production (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_waso_inc_landfilling.yaml | TX:WASO:INC_LANDFILLING] Increase landfilling (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_waso_inc_recycling.yaml | TX:WASO:INC_RECYCLING] Increase recycling (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 1.0
==================================================
==================================================
[transformation_enfu_adj_exports.yaml | TX:ENFU:ADJ_EXPORTS] Increase fuel exports (ENFU) | Start: 12
Strategy: strategy_NDC, Scalar value: 3.35
==================================================
==================================================
[transformation_enfu_adj_exports.yaml | TX:ENFU:ADJ_EXPORTS] Increase fuel exports (ENFU) | Start: 12
Strategy: strategy_LEP, Scalar value: 6.67
==================================================

In [21]:
# Load the transformations per strategy dictionary so we can pass it to the strategy handler
# You can also check here if the transformations in each strategy are correct

if ssp_transformation_cw is not None:
    logger.info("Loading transformations per strategy dictionary...")
    transformation_per_strategy_dict = excel_yaml_handler.get_transformations_per_strategy_dict()
    transformation_per_strategy_dict
    logger.info(f"Loaded transformations for strategies: {transformation_per_strategy_dict.keys()}")
else:
    logger.warning("No transformation handler available. Please check your config file.")

2026-03-03 12:30:53,414 - INFO - Loading transformations per strategy dictionary...
2026-03-03 12:30:53,415 - INFO - Loaded transformations for strategies: dict_keys(['strategy_NDC', 'strategy_LEP'])

### Creating new strategies
- You can create new strategies from scratch.
- You can also update existing ones.

In [22]:
# Creating new strategies by updating the strategy_definitions file.

if ssp_transformation_cw is not None:
    # You can edit this to add yours, as many as you want.
    csv_handler = StrategyCSVHandler(csv_file_path=STRATEGIES_DEFINITIONS_FILE_PATH, 
                                     yaml_dir_path=TRANSFORMATIONS_DIR_PATH, 
                                     yaml_mapping_file=STRATEGY_MAPPING_FILE_PATH, 
                                     transformation_per_strategy_dict=transformation_per_strategy_dict)
    csv_handler.add_strategy(strategy_group='PFLO', description='NDC', yaml_file_suffix='NDC')
    csv_handler.add_strategy(strategy_group='PFLO', description='LEP', yaml_file_suffix='LEP')
else:
    logger.warning("No transformation handler available. Please check your config file.")

INFO: Strategy code PFLO:NDC already exists in the strategy definitions. Strategy will be updated...
Updated row with strategy_code PFLO:NDC
INFO: Strategy code PFLO:LEP already exists in the strategy definitions. Strategy will be updated...
Updated row with strategy_code PFLO:LEP

**Manual tunning of some yamls**

In [23]:
# Temporary fix to add a parameter to the yaml files
from ruamel.yaml import YAML
yaml = YAML()
# tell it to keep your original quoting
yaml.preserve_quotes = True

def add_parameter_to_yaml_file(yaml_file_path, parameter_key, parameter_value):
   
    with open(yaml_file_path, 'r') as f:
        data = yaml.load(f)              # <-- ruamel.yaml keeps your formatting

        if 'parameters' not in data:
            raise ValueError(f"{yaml_file_path!r} has no ‘parameters’ key")
        
        data['parameters'][parameter_key] = parameter_value  # add your key

        with open(yaml_file_path, 'w') as f:
            yaml.dump(data, f)               # <-- dumps with the *same* quotes, indents, folds

In [24]:
increase_exports_path_ndc = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_enfu_adj_exports_strategy_NDC.yaml")
increase_exports_path_lep = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_enfu_adj_exports_strategy_LEP.yaml")
target_renewables_ndc = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_entc_target_renewable_elec_strategy_NDC.yaml")
target_renewables_lep = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_entc_target_renewable_elec_strategy_LEP.yaml")

In [25]:
add_parameter_to_yaml_file(
    increase_exports_path_ndc,
    "cats_enfu",
    ["fuel_natural_gas"]
)

add_parameter_to_yaml_file(
    increase_exports_path_lep,
    "cats_enfu",
    ["fuel_natural_gas"]
)

add_parameter_to_yaml_file(
    target_renewables_ndc,
    "dict_entc_renewable_target_msp",
    {
    # "pp_gas_ccs": 0.64,
    "pp_wind": 0.10,
    "pp_geothermal": 0.05,
    "pp_solar": 0.35
    }
)

add_parameter_to_yaml_file(
    target_renewables_ndc,
    "scale_non_renewables_to_match_surplus_msp",True
)

add_parameter_to_yaml_file(
    target_renewables_lep,
    "dict_entc_renewable_target_msp",
    {
    # "pp_solar": 0.20,
    # "pp_gas_ccs": 0.64,
    "pp_wind": 0.10,
    "pp_geothermal": 0.10
    }
)

In [26]:
# Set up the strategy codes you wish to run in ssp
strategies_to_run = [0,0,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,
                   2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,
                   3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010,3011,3012,3013,3014,3015,3016,3017,3018,3019,3020,3021,3022,3023,
                   4000,4001,4002,4003,4004,4005,6000,6001,
                   6003, 6004]
#strategies_to_run.extend(range(6005, 6046))

### We finished adding new transformation files and strategies so lets load them back

In [27]:
# then, you can load this back in after modifying (play around with it)
transformations = trf.Transformations(
    TRANSFORMATIONS_DIR_PATH,
    transformers = transformers,
)
tab = transformations.attribute_transformation.table

In [28]:
#  build the strategies -- will export to path
t0 = time.time()
strategies = trf.Strategies(
    transformations,
    export_path = "transformations",
    prebuild = True,
)

t_elapse = sf.get_time_elapsed(t0)
print(f"Strategies defined at {strategies.transformations.dir_init} initialized in {t_elapse} seconds")

Strategies defined at /Users/fabianfuentes/git/ssp_libya/ssp_modeling/transformations initialized in 7.54 seconds

In [29]:
strategies.attribute_table

,strategy_id,strategy_code,strategy,description,transformation_specification,baseline_strategy_id
0,0,BASE,Strategy TX:BASE,NaN,TX:BASE,1
1,1000,AGRC:DEC_CH4_RICE,Singleton - Default Value - AGRC: Improve rice...,NaN,TX:AGRC:DEC_CH4_RICE,0
2,1001,AGRC:DEC_EXPORTS,Singleton - Default Value - AGRC: Decrease Exp...,NaN,TX:AGRC:DEC_EXPORTS,0
3,1002,AGRC:DEC_LOSSES_SUPPLY_CHAIN,Singleton - Default Value - AGRC: Reduce suppl...,NaN,TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN,0
4,1003,AGRC:INC_CONSERVATION_AGRICULTURE,Singleton - Default Value - AGRC: Expand conse...,NaN,TX:AGRC:INC_CONSERVATION_AGRICULTURE,0
...,...,...,...,...,...,...
112,6041,WHIRLPOOL:TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_LEP,Remove TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_LEP...,NaN,TX:ENFU:ADJ_EXPORTS_STRATEGY_LEP|TX:ENTC:TARGE...,0
113,6042,WHIRLPOOL:TX:WASO:INC_ENERGY_FROM_BIOGAS_STRAT...,Remove TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY...,NaN,TX:ENFU:ADJ_EXPORTS_STRATEGY_LEP|TX:ENTC:TARGE...,0
114,6043,WHIRLPOOL:TX:WASO:INC_ENERGY_FROM_INCINERATION...,Remove TX:WASO:INC_ENERGY_FROM_INCINERATION_ST...,NaN,TX:ENFU:ADJ_EXPORTS_STRATEGY_LEP|TX:ENTC:TARGE...,0
115,6044,WHIRLPOOL:TX:WASO:INC_LANDFILLING_STRATEGY_LEP,Remove TX:WASO:INC_LANDFILLING_STRATEGY_LEP fr...,NaN,TX:ENFU:ADJ_EXPORTS_STRATEGY_LEP|TX:ENTC:TARGE...,0
116,6045,WHIRLPOOL:TX:WASO:INC_RECYCLING_STRATEGY_LEP,Remove TX:WASO:INC_RECYCLING_STRATEGY_LEP from...,NaN,TX:ENFU:ADJ_EXPORTS_STRATEGY_LEP|TX:ENTC:TARGE...,0

##  Build our templates
- let's use the default variable groupings for LHS

In [30]:
# Building excel templates, make sure to include the strategies ids in the strategies attribute as well as the baseline (0)
df_vargroups = _EXAMPLES("variable_trajectory_group_specification")

strategies.build_strategies_to_templates(
    # df_trajgroup = df_vargroups,
    # include_simplex_group_as_trajgroup = True,
    strategies = strategies_to_run,
)

0

# Finally, load SISEPUEDE and run it

In [31]:
country_name

'libya'

In [32]:
import sisepuede as si
# timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
ssp = si.SISEPUEDE(
    "calibrated",
    db_type = "csv",
    # id_str = f"sisepuede_run_2024-11-04T09:23:26.721580",
    initialize_as_dummy = not(energy_model_flag), # no connection to Julia is initialized if set to True
    regions = [country_name],
    strategies = strategies,
    # try_exogenous_xl_types_in_variable_specification = True,
    attribute_time_period=_ATTRIBUTE_TABLE_TIME_PERIOD
)

2026-03-03 12:32:13,862 - INFO - Successfully initialized SISEPUEDEFileStructure.
2026-03-03 12:32:13,863 - WARNING - Missing key dict_dimensional_keys: key time_series not found. Tables that rely on the time_series will not have index checking.
2026-03-03 12:32:13,863 - INFO - 	Setting export engine to 'csv'.
2026-03-03 12:32:13,864 - WARNING - No index fields defined. Index field values will not be checked when writing to tables.
2026-03-03 12:32:13,864 - INFO - Successfully instantiated table ANALYSIS_METADATA
2026-03-03 12:32:13,864 - WARNING - No index fields found in ATTRIBUTE_DESIGN. Initializing index fields.
2026-03-03 12:32:13,864 - INFO - Successfully instantiated table ATTRIBUTE_DESIGN
2026-03-03 12:32:13,865 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES. Initializing index fields.
2026-03-03 12:32:13,865 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES
2026-03-03 12:32:13,865 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS. Initializing index fields.
2026-03-03 12:32:13,865 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS
2026-03-03 12:32:13,865 - WARNING - No index fields found in ATTRIBUTE_PRIMARY. Initializing index fields.
2026-03-03 12:32:13,866 - INFO - Successfully instantiated table ATTRIBUTE_PRIMARY
2026-03-03 12:32:13,866 - WARNING - No index fields found in ATTRIBUTE_STRATEGY. Initializing index fields.
2026-03-03 12:32:13,866 - INFO - Successfully instantiated table ATTRIBUTE_STRATEGY
2026-03-03 12:32:13,866 - WARNING - No index fields found in ATTRIBUTE_TIME_PERIOD. Initializing index fields.
2026-03-03 12:32:13,866 - INFO - Successfully instantiated table ATTRIBUTE_TIME_PERIOD
2026-03-03 12:32:13,867 - WARNING - No index fields found in MODEL_BASE_INPUT_DATABASE. Initializing index fields.
2026-03-03 12:32:13,867 - INFO - Successfully instantiated table MODEL_BASE_INPUT_DATABASE
2026-03-03 12:32:13,867 - WARNING - No index fields found in MODEL_INPUT. Initializing index fields.
2026-03-03 12:32:13,867 - INFO - Successfully instantiated table MODEL_INPUT
2026-03-03 12:32:13,867 - WARNING - No index fields found in MODEL_OUTPUT. Initializing index fields.
2026-03-03 12:32:13,867 - INFO - Successfully instantiated table MODEL_OUTPUT
2026-03-03 12:32:13,868 - INFO - SISEPUEDEOutputDatabase successfully initialized IterativeDatabase.
2026-03-03 12:32:13,868 - INFO - Successfully initialized database with:
	type:	csv
	analysis id:	sisepuede_run_2026-03-03T12:32:13.541786
	fp_base_output:	/Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-03T12;32;13.541786/sisepuede_run_2026-03-03T12;32;13.541786_output_database
2026-03-03 12:32:13,868 - INFO - Running SISEPUEDE under template data mode 'calibrated'.
2026-03-03 12:32:13,868 - INFO - Initializing BaseInputDatabase
2026-03-03 12:32:14,581 - INFO - Initializing FutureTrajectories
2026-03-03 12:32:20,537 - INFO - Instantiating 1776 sampling units.
2026-03-03 12:32:20,552 - INFO - Iteration 0 complete.
2026-03-03 12:32:23,568 - INFO - Iteration 250 complete.
2026-03-03 12:32:25,280 - INFO - Iteration 500 complete.
2026-03-03 12:32:26,925 - INFO - Iteration 750 complete.
2026-03-03 12:32:28,650 - INFO - Iteration 1000 complete.
2026-03-03 12:32:30,322 - INFO - Iteration 1250 complete.
2026-03-03 12:32:32,076 - INFO - Iteration 1500 complete.
2026-03-03 12:32:33,718 - INFO - Iteration 1750 complete.
2026-03-03 12:32:33,884 - INFO - 	1776 sampling units complete in 13.35 seconds.
2026-03-03 12:32:33,890 - INFO - 	FutureTrajectories for 'libya' complete.
2026-03-03 12:32:33,891 - INFO - Initializing LHSDesign
2026-03-03 12:32:33,891 - INFO - LHSDesign.fields_factors_l reset successful.
2026-03-03 12:32:33,891 - INFO - LHSDesign.fields_factors_x reset successful.
2026-03-03 12:32:33,914 - INFO - 	LHSDesign for region 'libya' complete.
2026-03-03 12:32:33,915 - INFO - Generating primary keys (values of primary_id)...
2026-03-03 12:32:33,915 - INFO - Successfully initialized SISEPUEDEExperimentalManager.
2026-03-03 12:32:33,916 - INFO - Successfully initialized NemoMod temporary database path as /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-03-03 12:32:33,916 - INFO - Set Julia directory for modules and environment to '/Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/julia'.
2026-03-03 12:32:33,966 - INFO - Successfully read NemoMod input table data from /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/ref/nemo_mod/SpecifiedDemandProfile.csv
2026-03-03 12:32:33,969 - INFO - Successfully read NemoMod input table data from /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/ref/nemo_mod/AvailabilityFactor.csv
2026-03-03 12:32:34,021 - INFO - Importing Julia...

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

Precompiling NemoMod...
Info Given NemoMod was explicitly requested, output will be shown live
WARNING: Method definition parse_line(String) in module ConfParser at /Users/fabianfuentes/.julia/packages/ConfParser/b2fge/src/ConfParser.jl:95 overwritten in module NemoMod at /Users/fabianfuentes/.julia/packages/NemoMod/qatsV/src/config_functions.jl:16.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
   1338.9 ms  ? NemoMod
[ Info: Precompiling NemoMod [a3c327a0-d2f0-11e8-37fd-d12fd35c3c72]
WARNING: Method definition parse_line(String) in module ConfParser at /Users/fabianfuentes/.julia/packages/ConfParser/b2fge/src/ConfParser.jl:95 overwritten in module NemoMod at /Users/fabianfuentes/.julia/packages/NemoMod/qatsV/src/config_functions.jl:16.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Info: Skipping precompilation due to precompilable error. Importing NemoMod [a3c327a0-d2f0-11e8-37fd-d12fd35c3c72].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
2026-03-03 12:32:53,632 - INFO - Successfully initialized JuMP optimizer from solver module HiGHS.
2026-03-03 12:32:53,646 - INFO - Successfully initialized SISEPUEDEModels.
2026-03-03 12:32:53,650 - INFO - Table ANALYSIS_METADATA successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-03T12;32;13.541786/sisepuede_run_2026-03-03T12;32;13.541786_output_database/ANALYSIS_METADATA.csv.
2026-03-03 12:32:53,651 - INFO - Table ATTRIBUTE_DESIGN successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-03T12;32;13.541786/sisepuede_run_2026-03-03T12;32;13.541786_output_database/ATTRIBUTE_DESIGN.csv.
2026-03-03 12:32:53,653 - INFO - Table ATTRIBUTE_STRATEGY successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-03T12;32;13.541786/sisepuede_run_2026-03-03T12;32;13.541786_output_database/ATTRIBUTE_STRATEGY.csv.
2026-03-03 12:32:53,653 - INFO - Table ATTRIBUTE_TIME_PERIOD successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-03T12;32;13.541786/sisepuede_run_2026-03-03T12;32;13.541786_output_database/ATTRIBUTE_TIME_PERIOD.csv.
2026-03-03 12:32:54,328 - INFO - Table MODEL_BASE_INPUT_DATABASE successfully written to /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2026-03-03T12;32;13.541786/sisepuede_run_2026-03-03T12;32;13.541786_output_database/MODEL_BASE_INPUT_DATABASE.csv.

In [33]:
not(energy_model_flag)

False

In [ ]:
# This runs the model, make sure you edit key_stretegy with the strategy ids you want to execute include baseline (0)
dict_scens = {
    ssp.key_design: [0],
    ssp.key_future: [0],
    ssp.key_strategy: strategies_to_run,
}

ssp.project_scenarios(
    dict_scens,
    save_inputs = True,
    include_electricity_in_energy = energy_model_flag,
    # dict_optimizer_attributes = {"user_bound_scale": -7, }
)

2026-03-03 12:32:54,396 - INFO -
***	STARTING REGION libya	***

2026-03-03 12:32:55,645 - INFO - Trying run primary_id = 0 in region libya
2026-03-03 12:32:55,646 - INFO - Running AFOLU model
2026-03-03 12:32:55,843 - INFO - AFOLU model run successfully completed
2026-03-03 12:32:55,843 - INFO - Running CircularEconomy model
2026-03-03 12:32:55,867 - INFO - CircularEconomy model run successfully completed
2026-03-03 12:32:55,867 - INFO - Running IPPU model
2026-03-03 12:32:55,904 - INFO - IPPU model run successfully completed
2026-03-03 12:32:55,905 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-03 12:32:55,915 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-03 12:32:55,962 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-03 12:32:55,962 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)
2026-03-03 12:32:55,990 - INFO - 	Path to temporary NemoMod database '/Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite' not found. Creating...

2026-03-Mar 12:32:56.363 Opened SQLite database at /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-03-Mar 12:32:56.381 Added NEMO structure to SQLite database at /Users/fabianfuentes/anaconda3/envs/ssp_libya_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2026-03-Mar 12:33:12.148 Started modeling scenario. NEMO version = 2.2.0, solver = HiGHS.

2026-03-03 12:34:18,123 - INFO - NemoMod ran successfully with the following status: OPTIMAL
2026-03-03 12:34:18,137 - INFO - EnergyProduction model run successfully completed
2026-03-03 12:34:18,137 - INFO - Running Energy (Fugitive Emissions)
2026-03-03 12:34:18,161 - INFO - Fugitive Emissions from Energy model run successfully completed
2026-03-03 12:34:18,161 - INFO - Appending Socioeconomic outputs
2026-03-03 12:34:18,166 - INFO - Socioeconomic outputs successfully appended.
2026-03-03 12:34:18,168 - INFO - Model run for primary_id = 0 successfully completed in 82.52 seconds (n_tries = 1).
2026-03-03 12:34:18,184 - INFO - Trying run primary_id = 1001 in region libya
2026-03-03 12:34:18,185 - INFO - Running AFOLU model

2026-03-Mar 12:33:12.666 Started optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-03-Mar 12:33:31.371 Finished optimizing following years: [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012].
2026-03-Mar 12:33:31.450 Started optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
2026-03-Mar 12:34:17.984 Finished optimizing following years: [1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035].
set ['emission_co2e_co2_entc_bmass_processing_and_refinement_fp_hydrogen_gasification'] = 0 in energy production. FIX WITH NEW fp_hydrogen_gasification_biomass TECH.

2026-03-03 12:34:18,389 - INFO - AFOLU model run successfully completed
2026-03-03 12:34:18,389 - INFO - Running CircularEconomy model
2026-03-03 12:34:18,415 - INFO - CircularEconomy model run successfully completed
2026-03-03 12:34:18,415 - INFO - Running IPPU model
2026-03-03 12:34:18,455 - INFO - IPPU model run successfully completed
2026-03-03 12:34:18,455 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2026-03-03 12:34:18,465 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2026-03-03 12:34:18,513 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2026-03-03 12:34:18,514 - INFO - Running Energy model (Electricity and Fuel Production: trying to call Julia)

## Read simulations and check outputs

In [ ]:
# Read input and output files
df_out = ssp.read_output(None)
df_in = ssp.read_input(None)

In [ ]:
def plot_field_stack(
    df,
    fields,
    dict_format,
    time_col="time_period",
    primary_id=0,
    figsize=(18, 8),
    legend_loc='upper right',
    legend_bbox=(1.1, 1),
    ylabel="MT Emissions CO2e",
    xlabel="Time Period",
    title=None,
):
    """
    Plots a stack plot of the selected fields for a given primary_id.

    Args:
        df (pd.DataFrame): DataFrame containing output data.
        fields (list): List of column names to plot.
        dict_format (dict): Formatting dictionary for colors.
        time_col (str): Name of the time column.
        primary_id (int): Value of primary_id to filter.
        figsize (tuple): Figure size.
        legend_loc (str): Legend location.
        legend_bbox (tuple): Legend bbox_to_anchor.
        ylabel (str): Y-axis label.
        xlabel (str): X-axis label.
        title (str): Plot title.
    """
    fig, ax = plt.subplots(figsize=figsize)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if title:
        ax.set_title(title)

    df_plot = df[df[ssp.key_primary].isin([primary_id])]

    fig, ax = spu.plot_stack(
        df_plot,
        fields,
        dict_formatting=dict_format,
        field_x=time_col,
        figtuple=(fig, ax),
    )

    ax.legend(loc=legend_loc, bbox_to_anchor=legend_bbox, title="Fields")
    plt.show()

In [ ]:
# Define the fields to plot and the formatting dictionary
subsector_emission_fields = matt.get_all_subsector_emission_total_fields()

dict_format = dict(
    (k, {"color": v}) for (k, v) in
    matt.get_subsector_color_map().items()
)

In [ ]:
primary_ids_to_plot = df_out[ssp.key_primary].unique()

In [ ]:
# Plot the emissions stack for the primary_id 0 (which is the baseline)
for primary_id in primary_ids_to_plot:

    plot_field_stack(
        df_out,
        subsector_emission_fields,
        dict_format,
        primary_id=primary_id,
        title=f"Emissions Stack Plot for Primary ID {primary_id}"
    )

# Export Wide File

In [ ]:
all_primaries = sorted(list(df_out[ssp.key_primary].unique()))

# build if unable to simply read the data frame
if df_in is None:
    df_in = []
     
    for region in ssp.regions:
        for primary in all_primaries: 
            df_in_filt = ssp.generate_scenario_database_from_primary_key(primary)
            df_in.append(df_in_filt.get(region))
    
    df_in = pd.concat(df_in, axis = 0).reset_index(drop = True)




df_export = pd.merge(
    df_out,
    df_in,
    how = "left",
)



# check output directory 
dir_pkg = os.path.join(
    ssp.file_struct.dir_out, 
    f"sisepuede_summary_results_run_{ssp.id_fs_safe}"
)
os.makedirs(dir_pkg) if not os.path.exists(dir_pkg) else None


for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(dir_pkg, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        print(f"Warning: Table {tab} returned None.")


df_primary = (
    ssp
    .odpt_primary
    .get_indexing_dataframe(
        sorted(list(df_out[ssp.key_primary].unique()))
    )
)
    
df_primary.to_csv(
    os.path.join(dir_pkg, f"ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(dir_pkg, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

In [ ]:
# Getting the directory where the outputs are stored
ssp.file_struct.dir_out

In [ ]:
RUN_ID_OUTPUT_DIR_PATH = os.path.join(
    RUN_OUTPUT_DIR_PATH, 
    f"sisepuede_results_run_{ssp.id_fs_safe}"
)

os.makedirs(RUN_ID_OUTPUT_DIR_PATH, exist_ok=True)

df_primary.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, "ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        logger.warning(f"Warning: Table {tab} returned None.")

In [ ]:
RUN_ID_OUTPUT_DIR_PATH